### ISSUE TITLE
Instructions for self-hosting CouchDb

### ISSUE THREAD

**Issue by donalmacanri** [open-nomie/nomie6-oss#11]
It would be useful to provide instructions and a working docker-compose configuration for self-hosting Nomie and CouchDb together and getting them talking to each other.

**Comment by brandoncorbin** [comment]
Calling @RdeLange has he has the most experience with getting CouchDB up and running. I haven't really used it since v2 days.

**Comment by qcasey** [comment]
FWIW this `docker-compose.yml` has been working well for me:

```yml
version: '3.1'
services:
  nomie6:
    image: ghcr.io/qcasey/nomie6-oss:master
    restart: unless-stopped
    ports:
      - 5000:80

  couchdb:
    image: couchdb:3
    restart: unless-stopped
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=<USERNAME>
      - COUCHDB_PASSWORD=<PASSWORD>
    volumes:
      - db:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.d/docker.ini

volumes:
  db:
```

with a `couchdb.ini` of:

```ini
[HTTPD]
enable_cors = true

[chttpd]
enable_cors = true

[cors]
origins = *
credentials = true
methods = GET, PUT, POST, HEAD, DELETE
headers = accept, authorization, content-type, origin, referer, x-csrf-token
```

SSL on both services.
