### ISSUE TITLE
Failed to execute 'fetch' on 'Window':

### ISSUE THREAD

**Issue by ZL1LAC** [open-nomie/nomie6-oss#53]
Im using https://open-nomie.github.io/

I get this message when trying to setup couchdb and connect.

`Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: `

**Comment by donalmacanri** [comment]
This sounds like it might be a CORS issue, maybe ... how are you hosting your CouchDB database?

**Comment by ZL1LAC** [comment]
Hoisting on a docker container with the URL https://db.xxx.xyz and CORS is enabled.

<html>
<body>


Vivaldi | 5.7.2921.53 (Stable channel) (64-bit)
-- | --
Revision | 61f2a4332cf5c7762ce2b311a6ed597582dc95e3
OS | Windows 11 Version 22H2 (Build 22621.1265)
JavaScript | V8 11.0.226.16
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36


</body>
</html>

**Comment by ZL1LAC** [comment]
@donalmacanri you managed to look into this?  Screenshot of the error.

![image](https://user-images.githubusercontent.com/909007/220071676-80689247-60bb-4ec5-bad4-81e5e94d3dc9.png)

**Comment by donalmacanri** [comment]
I haven't been able to replicate the issue on Safari or Firefox (on Mac, although OS is unlikely to be the issue). I regularly use [OpenNomie](https://open-nomie.github.io/) with a CouchDB instance hosted on Cloudant.

Can you share any other details about your CouchDB configuration and you set it up?

**Comment by ZL1LAC** [comment]
What other details do you need?  Just let me know what other information you need and I'll get it.

**Comment by donalmacanri** [comment]
The two things that come to mind are your couchdb.ini file, and any relevant information related to how you've got running with HTTPS. Are you running it behind a reverse proxy?

**Comment by ZL1LAC** [comment]
Alright lets get all this information.  The CouchDB is accessible using a reverse proxy.

I'm running CouchDB in docker using this docker compose.
```
version: '3'
services:
  couchserver:
    image: matthiasg/rpi-couchdb:latest
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    volumes:
        - ./dbdata:/opt/couchdb/data
```
